In [1]:

import sys
import platform

print("Python version:", sys.version.split()[0])
print("Python executable:", sys.executable)
print("Platform:", platform.platform())

Python version: 3.13.16
Python executable: /usr/bin/python3
Platform: Linux-6.6.122+-x86_64-with-glibc2.39

In [2]:

%pip install pandas

import pandas as pd

print("Pandas version:", pd.__version__)

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Pandas version: 2.2.3

In [3]:

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [5]:

df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:

missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("Missing values per column:")
print(missing)

print("\nMissing percentage:")
print((missing / len(df) * 100).round(1))

Missing values per column:
deck           688
age            177
embarked         2
embark_town      2
dtype: int64

Missing percentage:
deck           77.2
age            19.9
embarked        0.2
embark_town     0.2
dtype: float64

In [7]:

numeric = df.select_dtypes(include="number")

cv = (numeric.std() / numeric.mean()).abs().sort_values(
    ascending=False
)

print("Coefficient of variation:")
print(cv.round(3))

print("\nLargest:", cv.index[0])

Coefficient of variation:
parch       2.112
sibsp       2.108
fare        1.543
survived    1.268
age         0.489
pclass      0.362
dtype: float64

Largest: parch

In [8]:

def inspect(path_or_url):
    import pandas as pd

    data = pd.read_csv(path_or_url)

    print("=" * 60)
    print("SOURCE:", path_or_url)
    print("SHAPE:", data.shape[0], "rows x", data.shape[1], "columns")

    print("\n--- DATA TYPES ---")
    print(data.dtypes)

    print("\n--- MISSING VALUES ---")
    missing = data.isnull().sum()
    missing = missing[missing > 0]

    if missing.empty:
        print("None")
    else:
        report = pd.DataFrame({
            "missing": missing,
            "percent": (missing / len(data) * 100).round(1)
        })
        print(report.sort_values("missing", ascending=False))

    print("\n--- NUMERIC SUMMARY ---")
    print(data.describe())

    return data


# Dataset 1: Titanic
titanic = inspect(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
)

============================================================
SOURCE: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv
SHAPE: 891 rows x 15 columns

--- DATA TYPES ---
survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

--- MISSING VALUES ---
             missing  percent
deck             688     77.2
age              177     19.9
embarked           2      0.2
embark_town        2      0.2

--- NUMERIC SUMMARY ---
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:

iris_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

iris = inspect(iris_url)

============================================================
SOURCE: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv
SHAPE: 150 rows x 5 columns

--- DATA TYPES ---
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

--- MISSING VALUES ---
None

--- NUMERIC SUMMARY ---
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:

penguins_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"

penguins = inspect(penguins_url)

============================================================
SOURCE: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv
SHAPE: 344 rows x 7 columns

--- DATA TYPES ---
species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

--- MISSING VALUES ---
                   missing  percent
sex                     11      3.2
bill_length_mm           2      0.6
bill_depth_mm            2      0.6
flipper_length_mm        2      0.6
body_mass_g              2      0.6

--- NUMERIC SUMMARY ---
       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [11]:

code = '''def inspect(path_or_url):
    import pandas as pd

    df = pd.read_csv(path_or_url)

    print("SOURCE:", path_or_url)
    print("SHAPE:", df.shape)

    print("\\nDATA TYPES")
    print(df.dtypes)

    print("\\nMISSING VALUES")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if missing.empty:
        print("None")
    else:
        print(pd.DataFrame({
            "missing": missing,
            "percent": (missing / len(df) * 100).round(1)
        }))

    print("\\nNUMERIC SUMMARY")
    print(df.describe())

    return df
'''

with open("inspect.py", "w") as f:
    f.write(code)

print("inspect.py saved successfully")

inspect.py saved successfully

In [12]:

import os

print("Current directory:", os.getcwd())
print("Files:", os.listdir("."))

Current directory: /content
Files: ['.config', 'inspect.py', 'AI Labs.zip', 'sample_data']